server:
  port: 8080
spring:
  application:
    name: student-management-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/sms_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update